<a href="https://colab.research.google.com/github/divyansh351/ML-Bootcamp-WOC/blob/main/KMeansClustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **K Means Clustering**

### **Importing necessary libraries and data**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/cyberlabs/emnist_data
test_path = '/content/drive/MyDrive/cyberlabs/emnist_data/emnist-letters-test.csv'
df_test = pd.read_csv(test_path, header=None)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/cyberlabs/emnist_data


### **Defining Functions**

In [3]:
def update_assignemnts(data,centroids):
  newc = []
  for i in range(len(data)):
      datt = data[i]
      newc.append(np.argmin(np.sum((datt.reshape((1,784))-centroids)**2,axis = 1)))
  return newc

In [4]:
def update_centroids(data,num_clusters,assignments):
    center = []
    for i in range(len(num_clusters)):
        center.append(np.mean([data[x] for x in range(len(data)) if assignments[x] == i], axis = 0))
    return center

### **Preprocessing the data and removing labels**

In [14]:
X = df_test.drop([0], axis = 1).values
print(X.shape)
print(X)
y = (df_test[0].values).reshape(df_test.shape[0],1)
print(y)

(14800, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[ 1]
 [ 1]
 [ 1]
 ...
 [19]
 [19]
 [19]]


In [17]:
centroids = np.random.normal(size=(38, 784))*0.001

### **Running the algorithm**

In [18]:
for i in range(1000):
    a = update_assignemnts(X, centroids)
    centroids = update_centroids(X, centroids, a)
    centroids = np.array(centroids)

In [19]:
a1=a[:800]
a2=a[801:1601]
a3=a[1601:2401]
a4=a[2401:3201]
a5=a[3201:4001]
a6=a[4001:4801]
a7=a[4801:5601]
a8=a[5601:6401]
a9=a[6401:7201]
a10=a[7201:8001]
a11=a[8001:8801]
a12=a[8801:9601]
a13=a[9601:10401]
a14=a[10401:11201]
a15=a[11201:12001]
a16=a[12001:12801]
a17=a[12801:13601]
a18=a[13601:14401]
a19=a[14401:]

In [22]:
dataset=[a1,a2,a3,a4,a5,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19]

### **Visualizing clusters**

In [23]:
def cluster_check(df, n):
  for i in range(38):
    count=0
    for j in range(n):
      if df[j]==i+1:
        count=count+1
    print('Cluster number',i+1,':' ,count)

In [24]:
for i in range(18):
  print(i+1)
  cluster_check(dataset[i], 800)
  print('\n')
  
print(19)
cluster_check(dataset[18], 399)

1
Cluster number 1 : 18
Cluster number 2 : 12
Cluster number 3 : 2
Cluster number 4 : 18
Cluster number 5 : 9
Cluster number 6 : 121
Cluster number 7 : 52
Cluster number 8 : 0
Cluster number 9 : 6
Cluster number 10 : 41
Cluster number 11 : 0
Cluster number 12 : 47
Cluster number 13 : 3
Cluster number 14 : 21
Cluster number 15 : 40
Cluster number 16 : 27
Cluster number 17 : 2
Cluster number 18 : 13
Cluster number 19 : 8
Cluster number 20 : 12
Cluster number 21 : 15
Cluster number 22 : 47
Cluster number 23 : 4
Cluster number 24 : 2
Cluster number 25 : 12
Cluster number 26 : 3
Cluster number 27 : 1
Cluster number 28 : 5
Cluster number 29 : 6
Cluster number 30 : 185
Cluster number 31 : 26
Cluster number 32 : 1
Cluster number 33 : 8
Cluster number 34 : 2
Cluster number 35 : 22
Cluster number 36 : 0
Cluster number 37 : 0
Cluster number 38 : 0


2
Cluster number 1 : 2
Cluster number 2 : 13
Cluster number 3 : 11
Cluster number 4 : 5
Cluster number 5 : 21
Cluster number 6 : 32
Cluster number 7 

### ***Calculating accuracy manually***

The first 800 values of a contain only capital and small A's. The capital A must be in one cluster and small a must be in other, Clusters 6 and 30 seem to contain A's assuming that the model worked correctly.

Accuracy of A = (121 + 185)*100/800

Similarly calculating accuracy of other letters.

In [25]:
accuA = (121+185)/8
accuB = (145+116)/8
accuC = (191+128)/8
accuD = (236+100)/8
accuE = (255+172)/8
accuF = 0  #Clustering data for e and f is same so assuming accuracy of f to be 0
accuG = (236+115)/8
accuH = (151+119)/8
accuI = (160+173)/8
accuJ = (278+243)/8
accuK = (187+216)/8
accuL = (285+121)/8
accuM = (220+188)/8
accuN = (323+286)/8
accuO = (240+60)/8
accuP = (294+247)/8
accuQ = (190+195)/8
accuR = (176+213)/8
accuS = (128+75)/4

In [26]:
accuTotal = (accuA+accuB+accuC+accuD+accuE+accuF+accuG+accuH+accuI+accuJ+accuK+accuL+accuM+accuN+accuO+accuP+accuQ+accuR+accuS)/19

In [27]:
accuTotal

45.86184210526316