<a href="https://colab.research.google.com/github/divyansh351/ML-Bootcamp-WOC/blob/main/polyRegNormalModelCubic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Polynomial Regression Normal Model with Cubic features***

### ***Importing necessary libraries and dataset*** 

In [1]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/cyberlabs/polynomial_data
train_path = '/content/drive/MyDrive/cyberlabs/polynomial_data/Polynomial_train.csv'
test_path = '/content/drive/MyDrive/cyberlabs/polynomial_data/Polynomial_test.csv'
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

/content/drive/MyDrive/cyberlabs/polynomial_data


### ***Preprocessing the dataset and adding cubic features***

In [3]:
X_train = df_train.drop(df_train.columns[[0, 4]], axis=1)
X_test = df_test.drop(df_test.columns[[0, 4]], axis=1)

In [4]:
trainData=df_train.values
Y_train = trainData[:, -1].reshape(trainData.shape[0], 1)
testData=df_test.values
Y_test = testData[:, -1].reshape(testData.shape[0], 1)

In [5]:
X_train['X2']=X_train['X']*X_train['X']
X_train['Y2']=X_train['Y']*X_train['Y']
X_train['Z2']=X_train['Z']*X_train['Z']
X_train['XY']=X_train['X']*X_train['Y']
X_train['YZ']=X_train['X']*X_train['X']
X_train['ZX']=X_train['Z']*X_train['X']
X_train['X2Y']=X_train['X2']*X_train['Y']
X_train['XY2']=X_train['X']*X_train['Y2']
X_train['X2Z']=X_train['X2']*X_train['Z']
X_train['XZ2']=X_train['X']*X_train['Z2']
X_train['Y2Z']=X_train['Y2']*X_train['Z']
X_train['YZ2']=X_train['Y']*X_train['Z2']
X_train['XYZ']=X_train['XY']*X_train['Z']
X_train['X3']=X_train['X']*X_train['X2']
X_train['Y3']=X_train['Y']*X_train['Y2']
X_train['Z3']=X_train['Z']*X_train['Z2']

In [6]:
X_test['X2']=X_test['X']*X_test['X']
X_test['Y2']=X_test['Y']*X_test['Y']
X_test['Z2']=X_test['Z']*X_test['Z']
X_test['XY']=X_test['X']*X_test['Y']
X_test['YZ']=X_test['X']*X_test['X']
X_test['ZX']=X_test['Z']*X_test['X']
X_test['X2Y']=X_test['X2']*X_test['Y']
X_test['XY2']=X_test['X']*X_test['Y2']
X_test['X2Z']=X_test['X2']*X_test['Z']
X_test['XZ2']=X_test['X']*X_test['Z2']
X_test['Y2Z']=X_test['Y2']*X_test['Z']
X_test['YZ2']=X_test['Y']*X_test['Z2']
X_test['XYZ']=X_test['XY']*X_test['Z']
X_test['X3']=X_test['X']*X_test['X2']
X_test['Y3']=X_test['Y']*X_test['Y2']
X_test['Z3']=X_test['Z']*X_test['Z2']

In [7]:
X_train = np.vstack((np.ones((X_train.shape[0], )), X_train.T)).T
X_test = np.vstack((np.ones((X_test.shape[0], )), X_test.T)).T

### ***Running the algorithm***

In [8]:
x = X_train
xT = np.transpose(x)
xT_x = np.dot(xT, x)
xT_xInv = np.linalg.pinv(xT_x)
tmp = np.dot(xT_xInv, xT)
thetaArr = np.dot(tmp, df_train["label"])
thetaArr

array([ 5.03635387e-01, -6.04222663e-01, -6.76571230e-01,  5.59042152e-01,
        5.04432664e-01, -5.03651957e+00,  4.03334082e+00, -3.20240725e+01,
        5.04432664e-01, -1.40760910e+01,  3.16041930e-03, -1.35929530e-02,
       -9.73236568e-03, -1.89056793e-02, -8.08514581e-03,  8.61590727e-03,
        1.00067203e-02,  2.40241891e-02,  8.26820971e-03, -7.49364052e-04])

### ***Predicting Labels***

In [9]:
predictedLabels = np.dot(X_test, thetaArr)
predictedLabels = predictedLabels.reshape(10000, 1)
predictedLabels

array([[ -671.04784137],
       [ -825.2600687 ],
       [  310.76019999],
       ...,
       [-1994.7097995 ],
       [   12.21593281],
       [  -51.56655213]])

In [10]:
Y_test

array([[ -657.66930949],
       [ -545.36252395],
       [  -75.04418664],
       ...,
       [-1771.64069421],
       [  -22.74692118],
       [  -64.85344575]])

In [11]:
def meanAbsoluteError(actual, predicted):
  return sum(abs(actual - predicted))/len(actual)

def meanSquaredError(actual, predicted):
  return sum(np.square(actual - predicted))/len(actual)

def rootMeanSquaredError(actual, predicted):
  return math.sqrt(meanSquaredError(actual, predicted))

def r2Score(actual, predicted):
  return 1 - sum(abs(np.square(actual - predicted)))/sum(abs(np.square(actual - np.mean(actual))))

In [12]:
MAE = meanAbsoluteError(Y_test, predictedLabels)
MSE = meanSquaredError(Y_test, predictedLabels)
RMSE = rootMeanSquaredError(Y_test, predictedLabels)
R2S = r2Score(Y_test, predictedLabels)
print("Mean Absolute Error:", MAE)
print("Mean Squared Error:", MSE)
print("Root Mean Squared Error:", RMSE)
print("R2 Score:", R2S)

Mean Absolute Error: [175.04212691]
Mean Squared Error: [54396.76622051]
Root Mean Squared Error: 233.2311433331972
R2 Score: [0.96258057]
