<a href="https://colab.research.google.com/github/divyansh351/ML-Bootcamp-WOC/blob/main/polyRegNormalModelLinFeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Polynomial Regression Normal Model with Linear features***

### ***Importing necessary libraries and dataset***

In [1]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/cyberlabs/polynomial_data
train_path = '/content/drive/MyDrive/cyberlabs/polynomial_data/Polynomial_train.csv'
test_path = '/content/drive/MyDrive/cyberlabs/polynomial_data/Polynomial_test.csv'
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

/content/drive/MyDrive/cyberlabs/polynomial_data


### ***Preprocessing the dataset***

In [3]:
X_train = df_train.drop(df_train.columns[[0, 4]], axis=1)
X_test = df_test.drop(df_test.columns[[0, 4]], axis=1)

In [4]:
trainData=df_train.values
Y_train = trainData[:, -1].reshape(trainData.shape[0], 1)
testData=df_test.values
Y_test = testData[:, -1].reshape(testData.shape[0], 1)

In [5]:
X_train = np.vstack((np.ones((X_train.shape[0], )), X_train.T)).T
X_test = np.vstack((np.ones((X_test.shape[0], )), X_test.T)).T

### ***Running the algorithm***

In [6]:
x = X_train
xT = np.transpose(x)
xT_x = np.dot(xT, x)
xT_xInv = np.linalg.pinv(xT_x)
tmp = np.dot(xT_xInv, xT)
thetaArr = np.dot(tmp, df_train["label"])
thetaArr

array([13.19465117,  1.68884616, -0.05236499,  0.33991762])

### ***Predicting Labels***

In [7]:
predictedLabels = np.dot(X_test, thetaArr)
predictedLabels = predictedLabels.reshape(10000, 1)
predictedLabels

array([[30.95089   ],
       [19.80397197],
       [ 5.92237616],
       ...,
       [25.58439482],
       [ 1.21739544],
       [27.92779037]])

In [8]:
Y_test

array([[ -657.66930949],
       [ -545.36252395],
       [  -75.04418664],
       ...,
       [-1771.64069421],
       [  -22.74692118],
       [  -64.85344575]])

In [9]:
def meanAbsoluteError(actual, predicted):
  return sum(abs(actual - predicted))/len(actual)

def meanSquaredError(actual, predicted):
  return sum(np.square(actual - predicted))/len(actual)

def rootMeanSquaredError(actual, predicted):
  return math.sqrt(meanSquaredError(actual, predicted))

def r2Score(actual, predicted):
  return 1 - sum(abs(np.square(actual - predicted)))/sum(abs(np.square(actual - np.mean(actual))))

In [10]:
MAE = meanAbsoluteError(Y_test, predictedLabels)
MSE = meanSquaredError(Y_test, predictedLabels)
RMSE = rootMeanSquaredError(Y_test, predictedLabels)
R2S = r2Score(Y_test, predictedLabels)
print("Mean Absolute Error:", MAE)
print("Mean Squared Error:", MSE)
print("Root Mean Squared Error:", RMSE)
print("R2 Score:", R2S)

Mean Absolute Error: [876.13794906]
Mean Squared Error: [1454181.62144485]
Root Mean Squared Error: 1205.894531642319
R2 Score: [-0.00032883]
